CourseWorkInterneShop/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('landing.urls')),
    url(r'^',include('landing.urls')),
    url(r'^',include('product.urls')),
    url(r'^',include('category.urls')),
    url(r'^',include('orders.urls'))
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

category/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
urlpatterns = [
    url(r'^category/(?P<category_id>\w+)/$',views.category,name='category'),#
]

orders/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^basket_adding/$',views.basket_adding,name='basket_adding'),
    url(r'^checkout/$',views.checkout,name='checkout'),
]

product/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^product/(?P<product_id>\w+)/$',views.product,name='product'),
]

category/models.py
from __future__ import unicode_literals

from django.db import models
class Category(models.Model):
    name = models.CharField(max_length=1024)
    meta_title = models.CharField(max_length=1024)
    meta_h1 = models.CharField(max_length=1024)
    meta_description = models.TextField()
    meta_keywords = models.CharField(max_length=1024)
    content = models.TextField()
    class Meta:
        managed = False
        db_table = 'category'
    def __str__(self):
        return "%s" % self.name

product/models.py
from __future__ import unicode_literals

from django.db import models
from orders.models import *

class Manufacturer(models.Model):
    name = models.CharField(max_length=1024)
    description = models.TextField()
    class Meta:
        managed = False
        db_table = 'manufacturer'
    def __str__(self):
        return "%s" % self.name

class Product(models.Model):
    name = models.CharField(max_length=1024)
    meta_title = models.CharField(max_length=1024)
    meta_h1 = models.CharField(max_length=1024)
    meta_description = models.TextField()
    meta_keywords = models.CharField(max_length=1024)
    short_description = models.TextField()
    description = models.TextField()
    enabled = models.BooleanField()
    price = models.DecimalField(max_digits=65, decimal_places=2,default=0)
    manufacturer=models.ForeignKey(Manufacturer,models.DO_NOTHING,db_column='manufacturer')
    category=models.ForeignKey('category.Category',models.DO_NOTHING,db_column='cid')
    is_active=models.BooleanField(db_column='is_active')
    class Meta:
        managed = False
        db_table = 'product'
    def __str__(self):
        return "%s" % self.name

class ProductImage(models.Model):
    product=models.ForeignKey(Product,models.DO_NOTHING)
    image=models.ImageField(upload_to="media/products_image")
    is_main=models.BooleanField(default=False)
    is_active=models.BooleanField(default=True)
    def __str__(self):
        return "%s" % self.image

class ProductRate(models.Model):
    rate = models.IntegerField()
    uid = models.ForeignKey('landing.User', models.DO_NOTHING, db_column='uid')
    pid = models.ForeignKey(Product,models.DO_NOTHING,db_column='pid')
    class Meta:
        managed = False
        db_table = 'product_rate'
    def __str__(self):
        return "%s %s" % (self.id.name,self.rate)


class ProductReview(models.Model):
    uid = models.ForeignKey('landing.User', models.DO_NOTHING, db_column='uid')
    date = models.DateTimeField(auto_now_add=True,auto_now=False)
    comment = models.TextField()
    pid = models.ForeignKey(Product, models.DO_NOTHING, db_column='pid')
    class Meta:
        managed = False
        db_table = 'product_review'
    def __str__(self):
        return "%s %s" % (self.uid.name,self.comment)

category/views.py
from django.shortcuts import render

from django.shortcuts import render
from category.models import *
from product.models import *
def category(request,category_id):
  category=Category.objects.get(id=category_id)
  product=Product.objects.filter(category_id=category_id)
  return render(request,'Category.html',locals())

product/views.py
from django.shortcuts import render
from product.models import *

def product(request,product_id):
    product=Product.objects.get(id=product_id)
    product_image=ProductImage.objects.filter(product_id=product_id)

    session_key=request.session.session_key
    if not session_key:
        request.session.cycle_key()
    print(request.session.session_key)
    return render(request, 'Product.html', locals())

templates/Category.html
{% extends 'base.html' %}
{% load static %}
{% block tittle%}
    {{ category.meta_title }}
{% endblock %}
{% block content %}
    <div class="text-center">
                    <h1>{{ category.name }}</h1>
    </div>
<div class="section">
        <div class="container">
            <div class="row">
                {% for produc in product  %}
                     <div class="col-lg-3">
                        <div class="product-item">

                                    <div>
                                        <a href="{%url 'product' produc.id  %}">
                                             {% for image_item in produc.productimage_set.all %}
                                                 {% if image_item.is_main%}
                                                     <div class="product-image-item">
                                                     <img src="{{ image_item.image.url }}" class="img-responsive">
                                                     </div>
                                                 {% endif %}
                                             {% endfor %}
                                        </a>
                                    </div>
                                    <div>
                                         {{ produc.short_description }}
                                    </div>
                                    <div>

                                        {{ produc.price }} USD
                                    </div>

                        </div>
                     </div>
                {% endfor %}
            </div>
        </div>
     </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%block tittle%}{{section.tittle }}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
    <div class="wrapper">
        <div class="wrapper-content">
        {% include 'navbar.html' %}

        {% block content %}
        {% endblock content %}
        </div>
    </div>

    {% include 'footer.html' %}
 <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <script src="{% static 'scripts.js' %}"></script>
</body>
</html>

templates/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block tittle %}
    Checkout
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
        {% if product_in_basket %}
        <div class="col-lg-6   col-lg-offset-3">
            <h3 class="text-center">

            </h3>
            <h5 class="text-center">Total_Price: </h5>

        <form class="form-horizontal" method="post">{% csrf_token %}

                <div class="form-group">
                    <div class="col-lg-6">

                    <label>Name</label>
                        <span class="form-error">{{ form.name.errors }}</span>
                    <input type="text" name="{{ form.name.html_name }}" class="form-control"
                    value="{{ request.POST.name }}">
                </div>
            </div>

             <div class="form-group">
                 <div class="col-lg-6">

                 <label>Phone</label>
                     <span class="form-error">{{ form.phone.errors }}</span>
                 <input type="text" name="{{ form.phone.html_name }}" class="form-control"
                 value="{{ request.POST.phone}}">
                 </div></div>
            <div class="form-group">
                <div class="col-lg-6">
                <label>email</label>
                         <span class="form-error">{{ form.email.errors }}</span>
                    <input type="text" name="{{ form.email.html_name }}" class="form-control"
                     value="{{ request.POST.email}}">
                </div>
            </div>
              <div class="form-group">
                 <div class="col-lg-6">

                 <label>Adress</label>
                     <span class="form-error">{{ form.adress.errors }}</span>
                 <input type="text" name="{{ form.adress.html_name }}" class="form-control"
                 value="{{ request.POST.adress}}">
             </div>

        </div>
        <table class="table text-center">
            <thead>
            <tr>
                <th>Name</th>
                <th>Count</th>
                <th>Price per item</th>
                <th>Total price</th>
            </tr>
            </thead>
            <tbody>
                    {% for product_in_basket in products_in_basket %}
                        <div class="hidden">
                     <input type="text" class="product_in_basket" name="product_in_basket_{{product_in_basket.id}}">

                 </div>
                        <tr>
                        <td>
                            {{ product_in_basket.product_id.name }}

                        </td>
                         <td>
                            {{ product_in_basket.count }}
                        </td>
                         <td>
                            {{ product_in_basket.price_per_item}}
                        </td>
                         <td>
                             <span class="total-product-in-basket-price">
                                  {{ product_in_basket.Full_price }}
                             </span>
                        </td>
                        </tr>


                {% endfor %}

            </tbody>
        </table>
            <div class="text-right">
                <b>Order price:{{total_price}}</b>
            </div>
            <hr>
            <div class="text-right">
                <button type="submit" class="btn btn-primary btn-large btn-lg">To order</button>
            </div>
        </form>

        </div>

            {% else %}
            <h3 class="text-center">There are no products in your shopping cart.</h3>
        {% endif %}
        </div>
    </div>
{% endblock %}

templates/footer.html
    <footer class="footer">
      <div class="container">
          <h3>footer</h3>
      </div>
    </footer>

templates/navbar.html
<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{%url 'home' %}">CourseWorkProject</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{%url 'home' %}">Home</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="active">
                <div class="basket-container">
                    <a href="">Basket<span id="basket_total_amount"></span><span id="basket_total_nmb">
                        {% if products_total_nmb %}
                           ( {{ products_total_nmb }})
                        {% else %}
                            (0)
                        {% endif %}
                    </span></a>
                    <div class="basket-items hidden">

                        <ul class="">
                              {% for product in products_in_basket %}
                                  <li>
                                      {{ product.product_id.name }} {{ product.count }} pieces {{ product.Full_price }} USD  <a class="delete-item" href="" data-product_id="{{ product.id }}">x</a>
                                  </li>
                                  <li>

 +                                <a href="{% url 'checkout'  %}">
 +                                    Create Order
 +                                </a>
 +                            </li>
                               {% endfor %}

                        </ul>
                    </div>
                </div>
            </li>
            <li class="">Telephone number</li>
            <li class="">othershortinfo</li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block tittle%}
    {{ product.meta_title }}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
            <div class="product-image-item">
                {% for image_item in product.productimage_set.all %}
                                                 {% if image_item.is_active%}
                                                     <div class="product-image-item">
                                                     <img src="{{ image_item.image.url }}" class="img-responsive">
                                                     </div>
                                                 {% endif %}
                                             {% endfor %}
            </div>
            </div>
            <div class="col-lg-6">
                <h1 class="text-center">
                    {{ product.name }}
                </h1>
                <div class="">
                    <p>
                        Price: {{ product.price }} USD
                    </p>
                </div>
                <div class="">
                    {{ product.description }}
                </div>
                <div>
                    <form id="form_buying_product" class="form-inline" action="{% url 'basket_adding' %}">{% csrf_token %}
                        <div class="form-group">
                        <input type="number" class="form-control" name="number" id ="number">
                        </div>
                        <div class="form-group">
                            <button type="submit" id="submit_btn" class="btn btn-success btn-buy"
                            data-product_id="{{ product.id }}"
                            data-name="{{ product.name }}"
                            data-price="{{ product.price }}">
                                Buy
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}